[package]
name = "polygon-pol-indexer"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time"] }
dotenv = "0.15"
ethers = { version = "2.0.0", features = ["abigen", "ws", "rustls"] }
rusqlite = { version = "0.29", features = ["bundled"] }
clap = { version = "4.3", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
rust_decimal = { version = "1.30", features = ["serde"] }
anyhow = "1.0"
log = "0.4"
env_logger = "0.10"
